#!/usr/bin/env python3
"""Report the startup and on-demand word cost of project skills."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


WORD = re.compile(r"[^\W_]+(?:['’-][^\W_]+)*", re.UNICODE)
LINK = re.compile(r"\[[^\]]+\]\(([^)\s]+)(?:\s+[^)]*)?\)")
SKILL_REFERENCE = re.compile(r"\$([a-z0-9-]+)")
FRONTMATTER = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
POLICY = re.compile(r"^\s*allow_implicit_invocation:\s*(true|false)\s*$", re.MULTILINE | re.IGNORECASE)


@dataclass(frozen=True)
class SkillScore:
    name: str
    auto_available: bool
    startup_words: int
    skill_path: Path
    skill_words: int
    linked_files: tuple[Path, ...]
    linked_words: int
    referenced_skills: tuple[str, ...]


def word_count(text: str) -> int:
    return len(WORD.findall(text))


def frontmatter(text: str) -> dict[str, str]:
    match = FRONTMATTER.match(text)
    if not match:
        raise ValueError("Missing YAML frontmatter")

    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        key, separator, value = line.partition(":")
        if not separator:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        fields[key.strip()] = value
    return fields


def auto_available(skill_dir: Path) -> bool:
    metadata = skill_dir / "agents" / "openai.yaml"
    if not metadata.is_file():
        return True

    match = POLICY.search(metadata.read_text(encoding="utf-8"))
    return match is None or match.group(1).lower() == "true"


def local_links(text: str, directory: Path) -> list[Path]:
    paths = []
    for target in LINK.findall(text):
        if target.startswith(("http:", "https:", "mailto:", "#")):
            continue
        path = target.split("#", 1)[0].split("?", 1)[0]
        paths.append((directory / path).resolve())
    return paths


def linked_files(entry_path: Path, skill_dir: Path) -> tuple[Path, ...]:
    root = skill_dir.resolve()
    visited = {entry_path.resolve()}
    queue = [entry_path.resolve()]
    linked: list[Path] = []

    while queue:
        current = queue.pop(0)
        for candidate in local_links(current.read_text(encoding="utf-8"), current.parent):
            try:
                candidate.relative_to(root)
            except ValueError:
                continue
            if not candidate.is_file() or candidate in visited:
                continue
            visited.add(candidate)
            linked.append(candidate)
            if candidate.suffix.lower() == ".md":
                queue.append(candidate)

    return tuple(sorted(linked))


def score_skill(skill_path: Path) -> SkillScore:
    content = skill_path.read_text(encoding="utf-8")
    fields = frontmatter(content)
    name = fields["name"]
    description = fields["description"]
    skill_dir = skill_path.parent
    available = auto_available(skill_dir)
    references = linked_files(skill_path, skill_dir)

    return SkillScore(
        name=name,
        auto_available=available,
        startup_words=word_count(f"{name} {description}") if available else 0,
        skill_path=skill_path.resolve(),
        skill_words=word_count(content),
        linked_files=references,
        linked_words=sum(word_count(path.read_text(encoding="utf-8")) for path in references),
        referenced_skills=tuple(sorted(set(SKILL_REFERENCE.findall(content)))),
    )


def path_from_skills_dir(path: Path, skills_dir: Path) -> str:
    return (Path(skills_dir.resolve().name) / path.relative_to(skills_dir.resolve())).as_posix()


def render_report(skills_dir: Path) -> str:
    scores = [score_skill(path) for path in sorted(skills_dir.glob("*/SKILL.md"))]
    startup_words = sum(score.startup_words for score in scores)
    auto_count = sum(score.auto_available for score in scores)
    skill_words = sum(score.skill_words for score in scores)

    linked_by_file: dict[Path, set[str]] = defaultdict(set)
    for score in scores:
        for path in score.linked_files:
            linked_by_file[path].add(score.name)
    linked_words = sum(word_count(path.read_text(encoding="utf-8")) for path in linked_by_file)

    skill_rows = "\n".join(render_skill_row(score, skills_dir) for score in scores)
    file_rows = "\n".join(render_file_rows(scores, linked_by_file, skills_dir))

    return f"""# Project skill context scores

Generated by `scripts/skill_context_scores.py`.

## What this measures

This report covers the skills tracked in this repository, not Codex system or plugin skills. A skill's full `SKILL.md` is loaded when that skill is used. It is not part of every conversation. At startup, Codex receives the names and descriptions of auto-available skills so it can select them. This report counts those semantic words separately from the full instruction text; it is a stable word metric, not an exact tokenizer count of Codex's full prompt.

Local files explicitly linked from a `SKILL.md` are counted recursively in that skill's on-demand total. Cross-skill references such as `$tdd` are listed but excluded: they are conditional invocations, not files loaded with the caller. External URLs, UI metadata, and unlinked assets are not counted.

## Startup baseline

Startup semantic words: {startup_words} across {auto_count} auto-available skills.

## Totals across separate files

- All `SKILL.md` files: {skill_words} words across {len(scores)} files.
- Linked local reference files: {linked_words} words across {len(linked_by_file)} files.
- All on-demand instructional files: {skill_words + linked_words} words across {len(scores) + len(linked_by_file)} files. This is a repository total, not a single conversation's context.

## Per-skill cost

| Skill | Auto | Startup words | `SKILL.md` words | Linked-file words | On-demand total | Linked local files | Referenced skills |
| --- | --- | ---: | ---: | ---: | ---: | --- | --- |
{skill_rows}

## File totals

| File | Words | Loaded when |
| --- | ---: | --- |
{file_rows}
"""


def render_skill_row(score: SkillScore, skills_dir: Path) -> str:
    linked = "<br>".join(
        f"{path_from_skills_dir(path, skills_dir)} ({word_count(path.read_text(encoding='utf-8'))})"
        for path in score.linked_files
    ) or "—"
    references = ", ".join(f"`{name}`" for name in score.referenced_skills) or "—"
    return (
        f"| `{score.name}` | {'Yes' if score.auto_available else 'No'} | {score.startup_words} | "
        f"{score.skill_words} | {score.linked_words} | {score.skill_words + score.linked_words} | "
        f"{linked} | {references} |"
    )


def render_file_rows(
    scores: list[SkillScore], linked_by_file: dict[Path, set[str]], skills_dir: Path
) -> list[str]:
    rows = []
    for score in scores:
        rows.append(
            f"| `{path_from_skills_dir(score.skill_path, skills_dir)}` | {score.skill_words} | "
            f"`{score.name}` is invoked |"
        )
    for path, names in sorted(linked_by_file.items()):
        invoked_by = ", ".join(f"`{name}`" for name in sorted(names))
        rows.append(
            f"| `{path_from_skills_dir(path, skills_dir)}` | "
            f"{word_count(path.read_text(encoding='utf-8'))} | linked from {invoked_by} |"
        )
    return rows


def parse_args() -> argparse.Namespace:
    repository_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skills-dir", type=Path, default=repository_root / "skills")
    parser.add_argument("--output", type=Path, default=repository_root / "skills" / "CONTEXT-SCORES.md")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    report = render_report(args.skills_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
